### ISSUE TITLE
Add Vets

### ISSUE THREAD

**Issue by firasrg** [firasrg/spring-petclinic-reactjs#5]
Hello @michaelisvy !

This is the issue related to your PR #4 . Please, from now on, any code changes must be linked to an issue. An issue must be opened witht title and description before doing any PR. 

Thanks in advance!

**Comment by michaelisvy** [comment]
thanks @firasrg , and thanks for your detailed review and guidelines!
I'll go through all your comments.

**Comment by michaelisvy** [comment]
hi @firasrg,
do you think you can merge my commits? Unless you have other feedback?
As there were a lot of items, I've created a separate issue for all the route-related items.
